### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by KOLANICH** [ssloy/tinyrenderer#1]
Здравствуйте.
http://habrahabr.ru/post/248723/#comment_8241713
1 Если у нас по 1 нормали к каждой точке, то мы неверно выразим негладкую поверхность (у которой нормали в особых точках вообще не существует). Вывод - к стыкам должно быть столько нормалей, сколько полигонов там стыкуются. То есть односторонние пределы. В вашем примере должно быть по 2 нормали: одна - на боковую сторону, другая - на верхнее основание. Тогда тонировки Фонга и Гуро должны дать одинаковые результаты в силу линейности умножения.
Как  вообще получают нормали к особым точкам, если их не существует, а они нужны?

2 Если же возьмём по 1й нормали, то либо верхнее основание будет затонированно неправильно (если возьмём нормали к боковым сторонам), либо боковые стороны (если возьмём нормали к верхнему основанию), либо всё будет затонированно неправильно.

3 И неплохо бы заполнить хабрапрофиль, в частности контактные данные, так как не все могут на Хабре писать.

**Comment by ssloy** [comment]
Дорый день. Для начала давайте определимся с тем, что нам нужно.
Если у нас есть низкополигональная модель, и нам нужно её выдать за гладкую, но при этом не добавлять треугольников,
то собственно для этого и были придуманы гуро-фонги.

Например, в этой модели, что вы даёте, логично определить одну нормаль на каждую вершину и спокойно их интерполировать.
Тот факт, что именно на этой модели Гуро ломается, не отменяет того, что изначально у них одни и те же цели.

Едем дальше, очень часто бывает нужно так, что нам нужно сглаживание, но не везде.
Например, если мы возьмём модель цилиндра, то мы захотим сгладить его круглый край, но стык цилиндра с основанием
сглаживать не хочется. Тогда мы на стыке определим по две нормали в каждой точке, а везде в остальных местах по одной.

**Comment by KOLANICH** [comment]
>Тогда мы на стыке определим по две нормали в каждой точке, а везде в остальных местах по одной.
Точнее по две одинаковых (иначе нарушится параллелизм по данным), так?
Но в точке могут стыковаться не 2 полигона, а больше, как дать все нормали  не нарушить параллелизм?

Линейность нарушается из-за того, что у нас поверхность на деле не гладкая? В пределе при неограниченном увеличении числа вершин различие (напр. подсчитанное как сумма квадратов разности всех компонент всех пикселов) между тонировками будет стремиться к нулю?

**Comment by ssloy** [comment]
Стоп. Мы говорим о разных вещах.
1) Разница в тонировке гуро и фонга просто в интерполяции, в пределе они дают один и тот же результат.
2) Строго говоря, для них нормаль задаётся не к вершине нашей треугольной сетки, а
к углу треугольника, прилегающего к данной вершине.

То есть, можно вообще забыть, что у нас есть много треугольников, можно ограничиться просто одним.
Мы зададим три разные нормали к трём углам треугольника, получим плавную заливку цветом, неважно, гуро или фонгом, это
мелочи.

Дальше. Если мы вдруг зададим все три нормали к углам треугольника просто равной нормали к плоскости треугольника,
то мы получим однотонный треугольник (flat shading).

Теперь представим два треугольника, которые имеют общее ребро. Мы дадим три одинаковые нормали одному треугольнику
и три других, но тоже одинаковых нормали второму треугольнику. Мы по-прежнему остались в режиме тонировки flat shading,
тем самым создав чёткое ребро между поверхностями. Но при этом мы бы могли на общем ребре дать общие нормали, тогда бы
мы сгладили переход от одного треугольника к другому. Но это не отменяет того факта, что у нас все треугольники живут
своей отдельной жизнью.

Вот пример - модель у нас абсолютно одна и та же, но
в левой картинке мы на вершину (точнее, на все углы, прилежащие к вершине) даём одну нормаль.
А в правой - мы разным углам, прилежащим к вершине, даём разные нормали.

http://wiki.polycount.com/w/images/5/51/BenMathis_SmoothingGroups_Excerpt.gif

**Comment by KOLANICH** [comment]
Понятно, спасибо.
