### ISSUE TITLE
internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by loloolk** [ssloy/tinyrenderer#100]
Sorry, if this is obvious, but when I followed your commands (with the small change of adding -G "MinGw" to the first cmake command) I got to the cmake --build . -j part, and it said 
C:\Users\{name}\OneDrive\Coding\C++\graphics\tinyrenderer\our_gl.cpp: In function 'void triangle(const vec4*, IShader&, TGAImage&, std::vector<double>&)':
C:\Users\{name}\OneDrive\Coding\C++\graphics\tinyrenderer\our_gl.cpp:58:1: internal compiler error: Segmentation fault
 }
and I dont know how to fix it.

**Comment by borailgar** [comment]
Quick guess: "internal compiler error" might be means that you need more memory to compile successfully. 
Although it seems you pass the flag -j only, not -j(n)
