### ISSUE TITLE
[not issue] Porting of tinyrenderer to Atari 2600

### ISSUE THREAD

**Issue by mohhingman** [ssloy/tinyrenderer#116]
Hello, ssloy thanks for writing tinyrenderer. It's a fantastic project! I was able to port the wireframe example to run on an Atari 2600 with the help of an ARM microprocessor. It was demonstrated on the Zeropage Homebrew show and a replay is now on youtube. The 3D rendering portion starts here:
https://youtu.be/gSrhrAZxXEY?t=2075
Cheers - Marco

**Comment by DouYuexi** [comment]
我已经收到您的邮件了，我将会尽快处理，保持联系！
