### ISSUE TITLE
Incompatible with modern C++?

### ISSUE THREAD

**Issue by UltraEngine** [ssloy/tinyrenderer#119]
I've been using this renderer in my 3D engine editor with great results to generate thumbnails for 3D models and materials. Unfotrunately, my project no longer will compile. Every single mat and vec constructor is producing an error saying "cannot convert from initializer list to mat<4, 4> (or whatever it is)". My project is using the C++20 standard.

Will this be fixed?

**Comment by ssloy** [comment]
What compiler do you use?

**Comment by ssloy** [comment]
fixed

**Comment by UltraEngine** [comment]
That was very fast, big thanks!

I'm using Visual Studio 2022, but my code is intended to compile with GCC and Mac (LLVM?) as well.
