### ISSUE TITLE
LLVM linker error

### ISSUE THREAD

**Issue by Nerd10000** [ssloy/tinyrenderer#137]
I don't know how can I fix this but the error is this : renderer-378788.o : error LNK2019: unresolved external symbol "public: __cdecl TGAImage::TGAImage(int,int,int)" (??0TGAImage@@QEAA@HHH@Z) referenced in function main
renderer-378788.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::set(int,int,struct TGAColor)" (?set@TGAImage@@QEAA_NHHUTGAColor@@@Z) referenced in function main
renderer-378788.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::write_tga_file(char const *,bool)" (?write_tga_file@TGAImage@@QEAA_NPEBD_N@Z) referenced in function main
renderer-378788.o : error LNK2019: unresolved external symbol "public: __cdecl TGAImage::~TGAImage(void)" (??1TGAImage@@QEAA@XZ) referenced in function main
a.exe : fatal error LNK1120: 4 unresolved externals
clang++: error: linker command failed with exit code 1120 (use -v to see invocation)

C:\Users\Dragon\Desktop\Fontos Fájlok\Rust\C\renderer>clang++  renderer.cpp
renderer.cpp:1:10: error: 'tga.h' file not found with <angled> include; use "quotes" instead
#include <tga.h>
         ^~~~~~~
         "tga.h"
1 error generated.

C:\Users\Dragon\Desktop\Fontos Fájlok\Rust\C\renderer>clang++  renderer.cpp
renderer-cdcff4.o : error LNK2019: unresolved external symbol "public: __cdecl TGAImage::TGAImage(int,int,int)" (??0TGAImage@@QEAA@HHH@Z) r@Z) referenced in function main
renderer-cdcff4.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::set(int,int,struct TGAColor)" (?set@TGAImage@mage@@QEAA_NHHUTGAColor@@@Z) referenced in function main
renderer-cdcff4.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::write_tga_file(char const *,bool)" (?write_tgte_tga_file@TGAImage@@QEAA_NPEBD_N@Z) referenced in function main
renderer-cdcff4.o : error LNK2019: unresolved external symbol "public: __cdecl TGAImage::~TGAImage(void)" (??1TGAImage@@QEAA@XZ) referencedenced in function main
a.exe : fatal error LNK1120: 4 unresolved externals
clang++: error: linker command failed with exit code 1120 (use -v to see invocation)

C:\Users\Dragon\Desktop\Fontos Fájlok\Rust\C\renderer>clang++  renderer.cpp

C:\Users\Dragon\Desktop\Fontos Fájlok\Rust\C\renderer>a.exe
Hell C++
C:\Users\Dragon\Desktop\Fontos Fájlok\Rust\C\renderer>clang++ renderer.cpp
renderer-fd737d.o : error LNK2019: unresolved external symbol "public: __cdecl TGAImage::TGAImage(int,int,int)" (??0TGAImage@@QEAA@HHH@Z) referenced in function main
renderer-fd737d.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::set(int,int,struct TGAColor)" (?set@TGAImage@@QEAA_NHHUTGAColor@@@Z) referenced in function main
renderer-fd737d.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::flip_vertically(void)" (?flip_vertically@TGAImage@@QEAA_NXZ) referenced in function main
renderer-fd737d.o : error LNK2019: unresolved external symbol "public: bool __cdecl TGAImage::write_tga_file(char const *,bool)" (?write_tga_file@TGAImage@@QEAA_NPEBD_N@Z) referenced in function main
renderer-fd737d.o : error LNK2019: unresolved external symbol "public: __cdecl TGAImage::~TGAImage(void)" (??1TGAImage@@QEAA@XZ) referenced in function main
a.exe : fatal error LNK1120: 5 unresolved externals
clang++: error: linker command failed with exit code 1120 (use -v to see invocation)

**Comment by DouYuexi** [comment]
我已经收到您的邮件了，我将会尽快处理，保持联系！

**Comment by Nerd10000** [comment]
Okay thank you .

**Comment by Nerd10000** [comment]
Was it fix?

**Comment by ssloy** [comment]
What is the build setup? Have you used the cmake description of the project?

**Comment by Nerd10000** [comment]
I didn't use cmake.

Dmitry V. Sokolov ***@***.***> ezt írta (időpont: 2023. dec.
15., P 7:47):

**Comment by ssloy** [comment]
I'd recommend using it instead of compiling individual c++ files by hand.
