### ISSUE TITLE
Не нашел как еще связатся

### ISSUE THREAD

**Issue by gNikro** [ssloy/tinyrenderer#2]
На хабре указан какой то не понятный не существующий эмэйл поэтому пишу тут.

Возможно была бы не плохая идея создать конференцию в скайпе или чем то подобном где люди могли бы общаться на тему и помогать решать друг другу вопросы. Сам давно хотел статьи глянуть но вот только вчера первую рассмотрел :)

Я вижу что на хабре идет активное общение по теме но к примеру я там не могу что то писать. А даже еслиб и мог то глупо там задавать вопросы какие то. Поэтому возможно создать конференцию была бы не плохая идея. Люди бы помогали друг другу развиваться

**Comment by ssloy** [comment]
Поправил ящик, спасибо большое за сигнал о сломанном.
Я не знаю, как создавать конференции. Можно, конечно, какой-нибудь IRC канал открыть...

Можете создать что-то, что будет максимально доступно (технически) людям?
Я пропиарю.

**Comment by gNikro** [comment]
Ну если верить статистики IRC свою популярность значительно потерял. Если раньше я всегда сидел с запущенным IRC клиентом то сейчас уже несколько лет как нет. Поэтому думаю не каждый будет его ставить. В то время как Skype используется многими. Но то же не факт что всеми :). Может быть есть какие то альтернативы лучше для живого общения.

Можно было бы в прочем и сообщество сделать для не живого общения что нибудь типа гугл групс. Но если не против скайп конференции то я ее могу создать.

**Comment by BG4444** [comment]
Вот у меня, например, скайп наглухо поломан по причине, имя которой PulseAudio.
Пока что желания ставить костыли (apulse) у меня нет.
Я предлагаю jabber. У меня jabber работает везде, где бы я не находился, если там есть интернет.

**Comment by gNikro** [comment]
ну в принципе можно и джаббер тоже доступно всем да и пользоватся им хоть
раз я думаю должны были все есть веб клиенты и тд. Так что не плохой вариант

**Comment by BG4444** [comment]
Конференция создана: 3d@conference.sudouser.ru

**Comment by gNikro** [comment]
нужно было название хорошее адепты треугольника например :D

**Comment by pSi-X** [comment]
gNikro, а какой у тебя скайпик?) А то как-то не круто, что здесь нельзя даже в почту человеку постучаться...

**Comment by gNikro** [comment]
capitan.picard :D

**Comment by pSi-X** [comment]
От же ж партизан :)
