### ISSUE TITLE
Lesson 2: What type is light_dir and where does it come from?

### ISSUE THREAD

**Issue by jimmyvh** [ssloy/tinyrenderer#23]
In order to calculate the light intensity, you need to know the light direction. The tutorial doesn't seem to mention at all how to obtain this light direction though.

In your example code, the light_dir variable gets used, but we don't see it getting defined anywhere.

**Comment by ssloy** [comment]
This light direction is chosen by hand, same as for the camera position. It is defined in main.cpp, line 14:

https://github.com/ssloy/tinyrenderer/blob/master/main.cpp#L14
