### ISSUE TITLE
Lession 2: question about the intensity math

### ISSUE THREAD

**Issue by neoedmund** [ssloy/tinyrenderer#24]
`float intensity = n*light_dir;`
`n` is a vec3f, `light_dir` is also a vec3f. 
Does it mean float intensity = n **mul** light_dir? but vec3f mul vec3f  is a vec3f, how did it cast to a float?
thanks.

**Comment by lexnewgate** [comment]
@neoedmund 
The **mul** has been override. It is actually **dot product**.
See the following func in[ geometry.h](https://github.com/ssloy/tinyrenderer/blob/c9c2da76429a54669f37c20ae432d31fd216a9c9/geometry.h#L46)
`template<size_t DIM,typename T> T operator*(const vec<DIM,T>& lhs, const vec<DIM,T>& rhs)`

**Comment by neoedmund** [comment]
Oh, I see. It worked with `dot`, thank you.
