### ISSUE TITLE
Rounding problem

### ISSUE THREAD

**Issue by osozero** [ssloy/tinyrenderer#27]
https://github.com/ssloy/tinyrenderer/blob/1cce85258d1f1cf75fd10fe4d62ebfdb669f8cf9/main.cpp#L62

Hi,

i think we should make uvP is Vec3f. When i tried it with Vec3i, texture coordinates were rounded to int and they broken. it works with vec3f.

**Comment by ssloy** [comment]
What is the range of your tex coordinates? What does it mean - broken? Can you provide any image?

**Comment by osozero** [comment]
We use the same model file. When i keep it as Vec3i the image is produced as https://imgur.com/a/s48qDmv. When i debug it, i see so many texture coordinates are rounded 1 or zero. Then i calculate uvP.x*1024 and uvP.y*1024. The result is as the link.

**Comment by ssloy** [comment]
In my code the texture coordinates vary between 0 and 1024 (actually, the image size). If you interpolate the original tex coords (those between 0 and 1), then yes, you need to use floating point.
