### ISSUE TITLE
Darboux basis

### ISSUE THREAD

**Issue by TylerWilson0407** [ssloy/tinyrenderer#31]
https://github.com/ssloy/tinyrenderer/wiki/Lesson-6bis:-tangent-space-normal-mapping#let-us-compute-darboux-basis-and-apply-the-perturbation-of-normals

Working my way through your lesson and got tripped up at this section.  When finding the Darboux frame, you are using the interpolated normal vector(`Vec3f bn = (varying_nrm*bar).normalize();` and `B.set_col(2, bn);`).  Since the interpolated normal isn't usually normal to the triangle face, and the `i, j` vectors are on the triangle face, this means that the `i, j, n` vectors aren't actually orthogonal, no?

Reading around online it seems that many implementations will calculate the tangent vectors on a per-vertex basis, by averaging the tangent vectors of each face that is touching the vertex, similar to how the normals are calculated.  Then the tangent can be interpolated like the normals within the triangle.

I'm guessing you're just using a bit of an approximation?  The results look fine so it seems to be working alright.

**Comment by ssloy** [comment]
Yes, the basis is not orthogonal. This is true even at an earlier stage: the tangent and bitangent vectors are not guaranteed to be orthogonal.

**Comment by TylerWilson0407** [comment]
Yeah, I'm seeing that now.  Seems there are a number of methods for calculating tangent basis.  I ended up implementing the method seen [here](http://www.terathon.com/code/tangent.html) to get the face tangent/bitangent vectors, and used a weighted average(by face area) to get per-vertex vectors.

Thank you!

**Comment by rap1ide** [comment]
Actually I stumbled upon the same thing. I couldn't find the answer to your question @ssloy:
_"Have you noticed that generally a (flat) triangle has a constant normal vector, whereas I used the interpolated normal in the last row of the matrix A? Why did I do it?"_

In your code the barycentric interpolation of normal bn was used. But why shouldn't I use the face normal?
(calculated as cross product n_face = cross([v2-v0, v1-v0]). Then I can pull matrix AI and even B out of the fragment shader call.
This would save a lot of computing time.

Why is bn interpolated?

**Comment by ssloy** [comment]
@rap1ide well, just try to replace the interpolated normal by the per-triangle constant one and check the result :)

**Comment by rap1ide** [comment]
Ok. I see. Seems tangent space map cannot overcome the flat shading "paperfold" effect. Guess the deviation of the normal then would have to be stronger inside the map (which would result to a not-so-much-bluish appearance).
Why can't the normal map in tangent space just be "stronger" and make the surface appear smooth? Wouldn't that work for  deformed meshes?
Im still stuck.

**Comment by ssloy** [comment]
The normal mapping framework is defined for smooth objects. In theory, you can perturb the constant-per-triangle normal, but then your texture won't be smooth, you have to "bake" all your triangles in it. And in practice you will have discontinuities on the edges that will come out as artefacts.

**Comment by rap1ide** [comment]
> The normal mapping framework is defined for smooth objects. In theory, you can perturb the constant-per-triangle normal, but then your texture won't be smooth, you have to "bake" all your triangles in it. And in practice you will have discontinuities on the edges that will come out as artefacts.

Thank you very much! And moreover: This is by far the best online-self-learning tutorials I've seen so far. I'm having a lot of fun.

**Comment by ssloy** [comment]
thank you for your kind words!
