### ISSUE TITLE
Not an issue: asking for guidance

### ISSUE THREAD

**Issue by ahmednofal** [ssloy/tinyrenderer#33]
Thank you very much for the wonderful content: 
In lesson 1 : at the end of the lesson there is a mention of
`The model.cpp file contains a simple parser.`
Should I use the file with the accompanying dependencies geometry.h and model.h, or should I implement them on my own?

**Comment by ssloy** [comment]
Well, it depends. I'd say, the goal is to learn. If you are absolutely sure you know how to implement it, you can skip that part. If you are unsure about all the tiny details, do not skip it.
