### ISSUE TITLE
Useful but confusing at times

### ISSUE THREAD

**Issue by hires** [ssloy/tinyrenderer#38]
This tutorial is very good, but there are often quite difficult sentences that introduce new terminology without any definition. Perhaps there should be a note that some amount of geometry or other kind of background knowledge is a prerequisite. I keep getting stuck trying to figure out the point of an example because the overall concept and the terminology used is not explained clearly.

**Comment by AliMustafa731** [comment]
I accept with you
this tutorial is really bad-documented and complex.
even though the idea of the program is very simple.
