### ISSUE TITLE
why i can't read texture

### ISSUE THREAD

**Issue by koooyf** [ssloy/tinyrenderer#39]
i can't read textures you provide

**Comment by ssloy** [comment]
can you provide the context please?

**Comment by koooyf** [comment]
for example, i can't open african_head_diffuse.tga in TGA Viewer,and i also can't use  tgaimage's api to read this file.
image.read_tga_file("african_head_diffuse.tga") will return "bad bpp (or width/height) value."
and i download source code to compile, it also fail.

**Comment by ssloy** [comment]
seems that you have corrupted files

**Comment by koooyf** [comment]
So where can I get correct files, thx.your lecture is amazing

**Comment by koooyf** [comment]
ok, i solve it. thank your answer,your lecture is amazing,i like it!
