### ISSUE TITLE
confusing description in troubleshooting article

### ISSUE THREAD

**Issue by matiTechno** [ssloy/tinyrenderer#40]
> Frequent bug: while sorting by y-coordinate, the vertices are sorted, but the data coming with the vertices is not.
> Gouraud shading, forgot to sort intensities

In my case I was calculating a barycentric coordinate of one vertex and assigning it to a different vertex by mistake.
The artifacts looked exactly the same as you presented, if it is the same problem then the description could be more informative.

**Comment by vchizhov** [comment]
It's probably left over from a previous version where scanline was used for rasterizing triangles.
