### ISSUE TITLE
Why reverse the element order when sampling from normal map

### ISSUE THREAD

**Issue by unknownue** [ssloy/tinyrenderer#44]
Here is the code of sampling normal from normal map:
https://github.com/ssloy/tinyrenderer/blob/907bb561c38e7bd86db8d99678c0108f2e53d54d/model.cpp#L86-L93

I can't understand why the element order of normal is reversed, that is, why not write the code like this:
```c++
for (int i=0; i<3; i++)
    res[i] = (float)c[i]/255.f*2.f - 1.f;
```

**Comment by ssloy** [comment]
It is a simple question of color packing in TGA images; they are stored in the BGR order and not RGB.
