### ISSUE TITLE
geometry.cpp проблемы

### ISSUE THREAD

**Issue by thx2010** [ssloy/tinyrenderer#5]
При прохождении вашего великолепного урока споткнулся об проблему 
Vec3 (to few arguments) 
компилирую Visual Studio 2013 но компилировал также на Dev C++, и получаю ошибку 
wrong number of template arguments

прикрепляю код программы который у меня не компилируется  
[3dtofile.zip](https://github.com/ssloy/tinyrenderer/files/69103/3dtofile.zip)

**Comment by ssloy** [comment]
Добрый день, файла не получил, но предполагаю, что ошибка в компиляции конструктора, который отвечает за округление.
Его можно просто убрать

**Comment by thx2010** [comment]
понятно но в таком случае будут артефакты изображения, ок постараюсь найти
замену такой специализации, напишу про результаты

2015-12-22 10:12 GMT+02:00 ssloy <notifications@github.com>:
