### ISSUE TITLE
Lesson 3 Extension: Source code for solution?

### ISSUE THREAD

**Issue by Tohaker** [ssloy/tinyrenderer#50]
I'm trying to do the texture mapping extension from part 3 but I can't seem to get over the mental hurdle of interpolating the texture triangle to the 3D one. I'd appreciate having the source code to reference and fill in the gaps in my knowledge.

**Comment by Dsm0** [comment]
@Tohaker I was looking for it too. Where did you find it?

**Comment by Tohaker** [comment]
https://github.com/ssloy/tinyrenderer/blob/1cce85258d1f1cf75fd10fe4d62ebfdb669f8cf9/main.cpp
