### ISSUE TITLE
Wiki leads to wrong tinyrenderer link.

### ISSUE THREAD

**Issue by kirawi** [ssloy/tinyrenderer#53]
Sends to: https://github.com/ssloy/tinyrenderer/wiki/Lesson-0:-getting-started
Instead of: https://github.com/ssloy/tinyrenderer/wiki/Lesson-0-getting-started
Notice the colon after 0.

**Comment by ssloy** [comment]
Where is the broken link? Can't find any. Thank you!

**Comment by kirawi** [comment]
https://github.com/ssloy/tinyrenderer/wiki

**Comment by ssloy** [comment]
Nice catch, thank you! Fixed.
