### ISSUE TITLE
question about lesson 4

### ISSUE THREAD

**Issue by wangzf88** [ssloy/tinyrenderer#55]
Hi Dmitry
        I am studying lesson 4 ，https://github.com/ssloy/tinyrenderer/tree/a175be75a8a9a773bdfae7543a372e3bc859e02f，After downloading this code, I encountered error c2976 (geometry.cpp  line 7) I am beginner to c++, i don't know why exist double template<> please help me thank you!

**Comment by BG4444** [comment]
Hi! What is your Visual Studio version?

**Comment by wangzf88** [comment]
my version is 2017，15.9.26

**Comment by Hajiren** [comment]
bro, delete the angle brackets after the Vec3 may help you to pass the compilation, like this:
template <> template <> Vec3<int>::Vec3(const Vec3<float> &v) : x(int(v.x+.5)), y(int(v.y+.5)), z(int(v.z+.5)) {
}

**Comment by wangzf88** [comment]
谢啦，兄弟，浙大的啊，我问题已经解决了，忘了关闭，麻烦你了

**Comment by Hajiren** [comment]
哈哈哈哈哈没事



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wangzf88"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午3:32
收件人: "ssloy/tinyrenderer"<tinyrenderer@noreply.github.com&gt;; 
抄送: "8年"<1024885318@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ssloy/tinyrenderer] question about lesson 4 (#55)





 
谢啦，兄弟，浙大的啊，我问题已经解决了，忘了关闭，麻烦你了

**Comment by wangzf88** [comment]
兄弟，过年好啊，给你拜个晚年，我又有空学习tinyrender了，我看到第6课时又遇到问题了，有空能指点我一下吗？因为我总是刷不出文章里的图，理解起来很费劲，不知道他为什么说采用切空间的法线可以根据模型动画改变方向，从而可以实现黑人的嘴张嘴时比闭嘴时亮，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2020年9月9日(星期三) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ssloy/tinyrenderer] question about lesson 4 (#55)





 哈哈哈哈哈没事 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2020年9月9日(星期三) 下午3:32 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [ssloy/tinyrenderer] question about lesson 4 (#55) 
 
 
 
 
 
   
 谢啦，兄弟，浙大的啊，我问题已经解决了，忘了关闭，麻烦你了
