### ISSUE TITLE
Lesson 2 return value of barycentric

### ISSUE THREAD

**Issue by lulier** [ssloy/tinyrenderer#57]
> Vec3f barycentric(Vec2i *pts, Vec2i P) { 
    Vec3f u = cross(Vec3f(pts[2][0]-pts[0][0], pts[1][0]-pts[0][0], pts[0][0]-P[0]), Vec3f(pts[2][1]-pts[0][1], pts[1][1]-pts[0][1], pts[0][1]-P[1]));
    /* `pts` and `P` has integer value as coordinates
       so `abs(u[2])` < 1 means `u[2]` is 0, that means
       triangle is degenerate, in this case return something with negative coordinates */
    if (std::abs(u[2])<1) return Vec3f(-1,1,1);
    return Vec3f(1.f-(u.x+u.y)/u.z, u.y/u.z, u.x/u.z); 
} 

According to the derivation of the lesson 2，i supposed the return value should be Vec3f(1.f-(u.x+u.y)/u.z, u.x/u.z , u.y/u.z); 
Am i right? or have i missed something here?

**Comment by ssloy** [comment]
Hum... the source code is correct I think. It says the following: Vec3f u = cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y));
therefore the confusion you have. Anyways, I found that this piece of code causes many troubles for the readers, and it is replaced by an explicit linear system solving in the most recent version of the code:

https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/our_gl.cpp#L25

**Comment by lulier** [comment]
> Hum... the source code is correct I think. It says the following: Vec3f u = cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y));
> therefore the confusion you have. Anyways, I found that this piece of code causes many troubles for the readers, and it is replaced by an explicit linear system solving in the most recent version of the code:
> 
> https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/our_gl.cpp#L25

thanks for the reply, i think you miss my point,
the result of cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y)) is (u * z ,v * z, z),  right? 
and what we want from the barycentric function is the barycentric coordinate, which should be (1-u-v ,u ,v),
therefore the return value should be Vec3f(1.f-(u.x+u.y)/u.z, u.x/u.z , u.y/u.z) instead of  Vec3f(1.f-(u.x+u.y)/u.z, u.y/u.z, u.x/u.z)
