### ISSUE TITLE
Hum... the source code is correct I think. It says the following: Vec3f u = cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y));

### ISSUE THREAD

**Issue by lulier** [ssloy/tinyrenderer#58]
Hum... the source code is correct I think. It says the following: Vec3f u = cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y));
therefore the confusion you have. Anyways, I found that this piece of code causes many troubles for the readers, and it is replaced by an explicit linear system solving in the most recent version of the code:

https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/our_gl.cpp#L25

_Originally posted by @ssloy in https://github.com/ssloy/tinyrenderer/issues/57#issuecomment-721119736_

according to the article, what we get from cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y)) is [u *z, v * z, z], and divided by z we can get [u, v, 1] 
and what we want from the barycentric function is [1-u-v, u, v]
therefore, we should return Vec3f(1.f-(u.x+u.y)/u.z, u.x/u.z, u.y/u.z) instead of Vec3f(1.f-(u.x+u.y)/u.z, u.y/u.z, u.x/u.z);

**Comment by ssloy** [comment]
Nope, according to the article, what we get from cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y)) is [v*z, u* z, z]. Note that in my code it is AC, AB, PA and not AB, AC, PA as in the article. Thus the result is [v, u, 1] and not [u, v, 1].

**Comment by lulier** [comment]
> Nope, according to the article, what we get from cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y)) is [v * z, u * z, z]. Note that in my code it is AC, AB, PA and not AB, AC, PA as in the article. Thus the result is [v, u, 1] and not [u, v, 1].



> Nope, according to the article, what we get from cross(Vec3f(AC.x, AB.x, PA.x), Vec3f(AC.y, AB.y, PA.y)) is [v * z, u * z, z]. Note that in my code it is AC, AB, PA and not AB, AC, PA as in the article. Thus the result is [v, u, 1] and not [u, v, 1].

oh, you are right, i write my code according to the formula 
![image](https://user-images.githubusercontent.com/4152491/98325003-b9a04080-2028-11eb-9f4b-b5a9691e08cc.png)
therefore i get the result  [u *z, v * z, z]
haha, maybe you should consider rewritting the formula or the code
