### ISSUE TITLE
Lesson Two:: final picture looks strange

### ISSUE THREAD

**Issue by Dora1994** [ssloy/tinyrenderer#59]
![image](https://user-images.githubusercontent.com/24545592/99144603-1f806e00-26a2-11eb-9fe1-005b030d43cd.png)
it looks like half stange and half normal, I am confuesed, Did anyone come across the same problem?

**Comment by ssloy** [comment]
invert the sign in the backface culling comparison

**Comment by ssloy** [comment]
also check this one https://github.com/ssloy/tinyrenderer/wiki/Visual-troubleshooting#lighting

**Comment by Dora1994** [comment]
> invert the sign in the backface culling comparison
thx a lot,  I realized what's wrong.
