### ISSUE TITLE
z-buffer

### ISSUE THREAD

**Issue by boddicheg** [ssloy/tinyrenderer#6]
Доброго времени суток!

Хочу сказать спасибо за ваши статьи на хабре о компьютерной графике - это то, что нужно таким новичкам, как я.
И, как полагается, у меня возникли некоторые вопросы по статье №3, и, когда у вас появится свободное время, прошу ответить.

В комментариях вы привели пример картинки с "дырками", когда mr. guyfawkes спросил у вас насчет хака
```
    P.x = j; P.y = t0.y+i; // a hack to fill holes (due to int cast precision problems)
```
Вы указали, что это ошибка с округлениями, и добавили на репозиторий конструктор копирования для Vec3i с округлением.

В чем моя проблема: 1.png в прикрепленных
Вроде бы очень похоже на вашу картинку с "дырками". НО, я использую double представление точки, т.е. все коодинаты:
```
      struct vertice {
        double x;
        double y;
        double z;
```
т.е. как видите, округлений особо нет(и да, я понимаю, что это медленне по сравнению с int)

Поскольку у меня координаты типа [-1.0, 1.0], то и прохожусь я по по координатам с помощью такого костыля:
```
    for (double y = f.y; y < t.y; y += m_delta)
```
где m_delta - некое магическое число(шаг), которое для 1.png  установлено в 0.001

если уменьшить шаг, то количество дырок уменьшается, но не пропадает(2.png - шаг установлен в 0.00035). Сами понимаете, что производительность падает при таком решении(у меня, для сравнения, 0.26105 сек для первого изображения, и 1.71324 сек для второго)

Нужна ваша конструктивная критика моих решений.
вот код метода рисования треугольника: [github](https://github.com/boddicheg/simple_wkit/blob/158a1db8d99238a97b60f1b5ab80f0653760b155/examples/2d/tinyrenderer/app.cpp#L109)

![1.png](https://cloud.githubusercontent.com/assets/2886378/11954683/10bd420c-a8b3-11e5-8022-328098aef886.png)
![2.png](https://cloud.githubusercontent.com/assets/2886378/11954684/10be2334-a8b3-11e5-84c2-fd0217b99c7b.png)

**Comment by ssloy** [comment]
Добрый день, собственно, это и есть проблема округления.
Попробуйте _перед_ отрисовкой всех треугольников округлить экранные координаты вершин.
ДС
