### ISSUE TITLE
Bug on face drawing code in lesson 1

### ISSUE THREAD

**Issue by tristancalderbank** [ssloy/tinyrenderer#60]
Please correct if this is wrong here but I think there's a bug in the lesson one code when we draw the obj mesh.

Specifically here: https://github.com/ssloy/tinyrenderer/blob/f6fecb7ad493264ecd15e230411bfb1cca539a12/main.cpp#L49

If a vertex has a x/y value equal to 1.0 or -1.0, then x or y becomes equal to `width`/`height`.

The problem is the data variable in TGAImage has a max width/height of (width - 1)/(height - 1) because its zero indexed.

What is hiding this bug is the fact that we just exit TGAImage::set if the x/y is out of bounds:

https://github.com/ssloy/tinyrenderer/blob/f6fecb7ad493264ecd15e230411bfb1cca539a12/tgaimage.cpp#L252

I think we're effectively cutting off the top/right edge of the image in the current lesson 1 code.

I think the solution here would be to do something like this?

```
int x0 = (v0.x+1.)*(width - 1)/2.;
int y0 = (v0.y+1.)*(height - 1)/2.;
int x1 = (v1.x+1.)*(width - 1)/2.;
int y1 = (v1.y+1.)*(height - 1)/2.;
```

Happened to notice this because I implemented a difference image drawing class (for BMP instead of TGA), and I didn't have the bounds check in the set method.

As an easier way to confirm this, just comment out the bounds check code in TGAImage::set and you will get an out of bounds exception.

**Comment by ssloy** [comment]
Well, i would not call it a bug, it depends really what you want to do (and what part of the pixel corresponds to a given coordinage)...

**Comment by tristancalderbank** [comment]
Sorry confused here, why wouldn't 1.0 in the obj file coordinates map to the max width/height value of the image array?
