### ISSUE TITLE
Question about TGA reading.

### ISSUE THREAD

**Issue by LuXiaoBai597** [ssloy/tinyrenderer#61]
Here is a statement about [TGA format](http://www.gamers.org/dEngine/quake3/TGA.txt) from WIKI.
It mentions that about ImageDescriptor, Bit 4 is reserved and Bit 5 represents origin is in lower left-hand corner or in higher left-hand.
In tgaimage.cpp, Bit 5 represents origin is in left-hand corner or in right-hand, and Bit 6 represents origin is lower corner or in higher corner.
Is there something wrong in the program or am I misunderstanding?

**Comment by ssloy** [comment]
Well, that is a good question, thank you for asking. I think that your link provides an incomplete specification.
Here is a screenshot from the original Truevision specification from 1991:

![image](https://user-images.githubusercontent.com/1029298/105148406-9f8fdd80-5b02-11eb-9a36-14f125b380c6.png)

**Comment by LuXiaoBai597** [comment]
I see, thank you!
