### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by dxxvi** [ssloy/tinyrenderer#7]
I wish there were a java and/or javascript version (I don't know C++ :-( ).

**Comment by ssloy** [comment]
My source code is irrelevant. The main point is in the accompagnying text. You should program it for yourself.

Here is an example of an early attempt in js:

http://jsfiddle.net/2wvyga24/24/

**Comment by mikeschuld** [comment]
Agree completely. I am putting together a C# version for my own practice and benefit and will eventually use that as my notes to help teach a similar course.

**Comment by ssloy** [comment]
Hello Michael, will you make your repository / screenshots public?

**Comment by schovi** [comment]
@dxxvi Hi, luckily for you I am playing with that in JS. There is my playground https://github.com/schovi/js-3d-render-playground

It is lot a mess (because it is just playground :) ). Maybe sometime I will clean it up. And split it into steps like in this `tinyrenderer`

**Comment by billhsu** [comment]
Here's my js implementation :) https://github.com/billhsu/renderer.js

**Comment by ssloy** [comment]
Thank you!

**Comment by bermanmaxim** [comment]
Not an issue, just a comment. I have not yet started but I can tell this is an amazing resource to get a deep understanding of rendering, and I am using this as an excuse to improve my C++ skills. Thanks a lot @ssloy for putting this together!
