### ISSUE TITLE
vertex normals in african_head model broken and inconsistent?

### ISSUE THREAD

**Issue by mpalomas** [ssloy/tinyrenderer#73]
Hi,

So I was trying to implement the Gouraud shading part, chapter 5 I believe, but ended up mostly with black image, with only a couple of whitish pixels at various places. Very weird.

I looked into my normal interpolation code based on barycentric coordinates and it looked fine. After a bit of troubleshooting, I came to the conclusion that it was the input vertex normals (read from the african_head obj) that were wrong.

I opened the obj in Blender and indeed the normals are all over the place : some outwards, some inwards, no consistency. So yeah I believe the african_head model vertex normals are broken.

My solution was to recompute the vertex normals in my obj parser (first compute face normals with consistent winding, then add to each vertex, finally normalize). And my Gouraud shading now appears to be good.

**Comment by ssloy** [comment]
Hello @mpalomas , it surprises me, here is a screenshot of the model in my blender:
![image](https://user-images.githubusercontent.com/1029298/113839356-e8fdd980-978f-11eb-88d4-59b3d4f089f4.png)

**Comment by mpalomas** [comment]
Interesting... I have re-opened the obj in both Blender and MeshLab, and this time I get the same as you : correct normals. 
I could swear when I opened it this morning there were half of normals in the wrong direction... I have no clue why I saw it once.
It seems I have an awkward bug in my code which only happens with normals in the obj. If I recompute them, my bug is gone.
Anyway it's on my side, sorry for the noise. I'm doing this in Rust and writing everything from scratch my own way, so I don't really copy your C++ code.

**Comment by ssloy** [comment]
Ouch. Good luck with finding the bug, keep me updated!

**Comment by mpalomas** [comment]
I found my bug, in case anyone is facing a similar issue.
So, for some reasons, if I negate all the vertex normals from the obj, meaning I do
`
let normal = normal * -1.0
`
Then it works, perfect Gouraud shading lol! And indeed now the "negated normal" is pretty much the same than the one I can compute from face normals interpolated to vertices.
Now I need to understand why I have this bug in the first place, and fix the root cause properly!
