### ISSUE TITLE
Texture Mapping Problem

### ISSUE THREAD

**Issue by Grayfoxlove95gas** [ssloy/tinyrenderer#74]
The home assignment of add texture to head model rendered by orthographic projection 
i interpolate uv coordinate by point P barycentric coordinate of every screen space triangle,then use interpolated uv to getpixel from diffuse imagedata.
now the render result is like this kind of thing
why a small human face displayed in one triangle face and why all the triangle textures be chaos？
here’s the result
![GDI软件光栅化渲染器 2021-04-13 14_10_11](https://user-images.githubusercontent.com/33934967/114504954-397aa880-9c62-11eb-9a4a-b26bfd83eacd.png)

**Comment by ssloy** [comment]
I'd say you have tex coords messed up. Check your .obj file parser, the rendering part seems to be fine.

**Comment by Grayfoxlove95gas** [comment]
> I'd say you have tex coords messed up. Check your .obj file parser, the rendering part seems to be fine.

thanks for your reminding，i found that i wrote a function only for get data of vertex coords，but i incorrectly used it for tex coords.so in the end every triangle interpolated  vert coords for getting pixel，that‘s the problem.
Now i have correct render result
![image](https://user-images.githubusercontent.com/33934967/114667548-2a632b80-9d32-11eb-9bf8-4d85417aa1d1.png)

**Comment by YashKarthik** [comment]
ran into a very similar issue two years later; thanks!
