### ISSUE TITLE
lesson 1:where is the "model" method "face()"?

### ISSUE THREAD

**Issue by beautyseeker** [ssloy/tinyrenderer#81]
this is lesson 1:use line render algorithm to draw model "african_head.obj",
`Model* model = new Model{"obj/african_head.obj"};

    TGAImage image(width, height, TGAImage::RGB);
    for (int i=0; i<model->nfaces(); i++) {
        std::vector<int> face = **model->face(i)**;
        for (int j=0; j<3; j++) {
            vec3 v0 = model->vert(face[j]);
            vec3 v1 = model->vert(face[(j+1)%3]);
            int x0 = (v0.x+1.)*width/2.;
            int y0 = (v0.y+1.)*height/2.;
            int x1 = (v1.x+1.)*width/2.;
            int y1 = (v1.y+1.)*height/2.;
            line(x0, y0, x1, y1, image, white);
        }
    }`
but I didn't find "face()"method in model head file
`class Model {
private:

    std::vector<vec3> verts_;     // array of vertices
    std::vector<vec2> uv_;        // array of tex coords
    std::vector<vec3> norms_;     // array of normal vectors
    std::vector<int> facet_vrt_;
    std::vector<int> facet_tex_;  // indices in the above arrays per triangle
    std::vector<int> facet_nrm_;
    TGAImage diffusemap_;         // diffuse color texture
    TGAImage normalmap_;          // normal map texture
    TGAImage specularmap_;        // specular map texture
    void load_texture(const std::string filename, const std::string suffix, TGAImage &img);
public:

    Model(const std::string filename);
    int nverts() const;
    int nfaces() const;
    vec3 normal(const int iface, const int nthvert) const;  // per triangle corner normal vertex
    vec3 normal(const vec2 &uv) const;                      // fetch the normal vector from the normal map texture
    vec3 vert(const int i) const;
    vec3 vert(const int iface, const int nthvert) const;
    vec2 uv(const int iface, const int nthvert) const;
    TGAColor diffuse(const vec2 &uv) const;
    double specular(const vec2 &uv) const;
};`

**Comment by longlongvip** [comment]
New code has no face() function
