### ISSUE TITLE
It should be (i<=0)

### ISSUE THREAD

**Issue by kyriewxcode** [ssloy/tinyrenderer#84]
https://github.com/ssloy/tinyrenderer/blob/1cce85258d1f1cf75fd10fe4d62ebfdb669f8cf9/geometry.h#L21

**Comment by ssloy** [comment]
yup, thanks, that is a bug that was fixed 

https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/geometry.h#L76
