### ISSUE TITLE
Question about double precision and barycentric method implementation.

### ISSUE THREAD

**Issue by atomicapple0** [ssloy/tinyrenderer#88]
Hi, I am implementing the barycentric method for the triangle rasterizer in lesson 2. My source is ([here](https://github.com/atomicapple0/tinyrenderer/commit/ea248c615bba5a3e5754d1332328a83c9a66e5ae)).

In the the barycentric method, I have the following:
```
Vec3f barycentric(Vec2i *pts, Vec2i P) {
  Vec3f S =
  Vec3f(pts[2][0] - pts[0][0],
	pts[1][0] - pts[0][0],
	pts[0][0] - P[0]) ^
  Vec3f(pts[2][1] - pts[0][1],
	pts[1][1] - pts[0][1],
	pts[0][1] - P[1]);
  double up, vp, s, u, v;
  up = S.x; vp = S.y; s = S.z;
  u = up / s; v = vp / s;
  if (std::abs(s) < 1) {
    return Vec3f(-1,-1,-1);
  }
  return Vec3f(1.-(up+vp)/s, u, v);
}
```
With the above code, the output tga looks as expected:
![image](https://user-images.githubusercontent.com/30697412/146681161-166091df-40f0-4d03-bdbf-41f8c2c506dc.png)

However, by changing only the last line to: 
```return Vec3f(1.-up/s-vp/s, u, v);```
There are random black specks that are not colored in along the edges of triangles:
![image](https://user-images.githubusercontent.com/30697412/146681214-44fba458-1d01-4de3-858a-6451c84093d1.png)

I suspect this is some issue with precision with double division. I would have never been able to figure this out myself if I wasn't able to directly compare my own code with the provided code snippets. Anyone have a better explanation about why this is the case and when to look out for this error in the future?

**Comment by DouYuexi** [comment]
我已经收到您的邮件了，我将会尽快处理，保持联系！

**Comment by ssloy** [comment]
Yup, floating point precision issues, no biggie. Try comparing with a small negative value (like -.01) here instead of zero:
https://github.com/atomicapple0/tinyrenderer/blob/7f51718971f009840851276bb449eecd3cb8ec60/main.cpp#L102
This will make the traingles a bit thicker, and hopefully filling the gaps.

**Comment by atomicapple0** [comment]
Thanks a lot, that fixed the issue.
