### ISSUE TITLE
Change the background color of formula picutres in wiki pages

### ISSUE THREAD

**Issue by alanjian85** [ssloy/tinyrenderer#92]
GitHub has introduced a new feature called dark theme lately, but it doesn't fit well in this tutorial, formula pictures in the wiki page have transparent background and black font color, it causes they are hard to see from the dark-theme-enabled client, it will be better if those pictures' background are opaque.

P.S. I have to say sorry for my english, it's not my native language :P

**Comment by ssloy** [comment]
but then won't you read black text on black background ???

**Comment by alanjian85** [comment]
I think making the background be white is better, you can then see black text clearly from both black and default(white) theme.

**Comment by lucafaggianelli** [comment]
Github recently added a feature to support images on dark and light themes, the idea is that you can create 2 images (1 for dark themes and 1 for light themes) and then GH will display the appropriate one:

https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
